### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: CDUSEC
# description: This will be meta HTML tag content. This can be ignored.
description: Charles Darwin University Cyber Security Club
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: CDUSEC
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: CDU Cyber Security Club
# email: Your E-Mail address for the email button.
email: example@a.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
# > github_username: cdusec
# > codepen_username: exampleUser
# > dev_username: exampleUser
linkedin_username: CDUCyberSecurityClub
# >twitter_username: exampleUser
facebook_username: CDU-Cyber-Security-Club-110602461772119
teams_username: 19%3arnfa4iQpDaGoLwxH_NZqHTSWL5RCIhex-adFsccMP7Y1%40thread.tacv2/conversations?groupId=6bdadcfd-5ea5-445e-9e9f-f1e3f3ecd6b7&tenantId=9f248767-8e1a-42f3-836f-c092ab95ff70

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Us
# about_me_description: This will be displayed under the title.
about_me_description: We're an affiliated, not-for-profit student group established in August 2022.<br><br>We aim to provide a student-led platform that introduces its members to cyber security and advance their knowledge through workshops and activities, to legally and ethically improve the cyber security skills of our members, and to represent the university in cyber security competitions.<br><br>Our mission is to encourage interest in and advocate best practices in cyber security, aid learning and promote teamwork through competitive experiences.<br><br>Our Core Values are:<ul><li>Integrity - maintain an ethical culture of trust, respect and open communication</li><li>Growth - continuous improvement not just individually and within the Club but also foster growth in the community through contribution and cooperation</li><li>Passion - nurture and cultivate passion about educating, leading, innovating, serving and making a positive impact.</li></ul>

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Sponsors

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Timeline of Events
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
# > cv_download_link: https://example.com/

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: false
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Upcoming Events
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: false
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact Us
# contact_description: This will be displayed under the title.
contact_description: We welcome inquiries from individuals, businesses, and organizations who share our commitment to our cause. Your support is essential to help us achieve our goals. If you're interested in making a contribution, sponsoring an event, or supporting our work in any other way, please get in touch with us using the links below.

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: cdusec/cdusec.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
